services:
  robot-webcontrol:
    container_name: robot-webcontrol
    build: 
      context: .
      dockerfile: Dockerfile
      tags:
        - ${DOCKER_REGISTRY}/$DOCKER_USERNAME/robot-webcontrol:$VERSION_TAG
        - ${DOCKER_REGISTRY}/$DOCKER_USERNAME/robot-webcontrol:latest
    image: ${DOCKER_REGISTRY}/$DOCKER_USERNAME/robot-webcontrol
    restart: unless-stopped

    environment:
      IP_ADDRESS: ${IP_ADDRESS}
      PORT: ${PORT}
      MQTT_SERVER: ${MQTT_SERVER}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_USER: ${MQTT_USER}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      WEBCAM_STREAM_URL: ${WEBCAM_STREAM_URL}
      WEBCAM_STREAM_PORT: ${WEBCAM_STREAM_PORT}
    ports:
      - '${PORT}:${PORT}'
    networks:
      - home-net
      
networks:
  home-net:
    driver: bridge